#
#  fancy logo here that I'm too lazy to add
#

#Enable mysql database storage
mysql-enabled: true

#Information for MySQL
#Don't mess with this if you aren't using it
mysql:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: ''
  database: 'sm'

#Prefix for all messages
message-prefix: '&7[&cRuneCraft&7]'

#Option for debugging in console
debug-mode: false